backend:
   name: git-gateway
collections:
   -  name: 'blog'
      label: 'Blog'
      folder: 'posts'
      fields:
         -  { label: 'Title', name: 'title', widget: 'string' }
         -  { label: 'Date', name: 'date', widget: 'default' }
         -  { label: 'Author', name: 'author', widget: 'string' }
         -  { label: 'Body', name: 'body', widget: 'markdown' }
media_library:
   name: cloudinary
   config:
      cloud_name: dbtvvoadc
      api_key: 851177547586169
      default_transformations:
         -  fetch_format: auto
            quality: auto
            width: 400
            crop: scale
